name: Deploy to GitHub Pages via angular-cli-ghpages

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        ng deploy --base-href=/angular-githubpages/ --name="Sinan Nar" --email=sinan.nar@gmail.com --base-href=/angular-githubpages/
